sudo: required
services:
    - docker
    
before_install
    - docker build -t sunnymishra0389/docker-react-testimage -f ./client/Dockerfile.dev ./client
    
script:
    - docker run sunnymishra0389/docker-react-testimage npm test -- --coverage
    
after_success:
    - docker build -t sunnymishra0389/multi-client ./client
    - docker build -t sunnymishra0389/multi-nginx ./nginx
    - docker build -t sunnymishra0389/multi-server ./server
    - docker build -t sunnymishra0389/multi-worker ./worker
    
    
    