language: generic
sudo: required
services:
    - docker
    
before_install:
    - docker build -t sunnymishra0389/docker-react-testimage -f ./client/Dockerfile.dev ./client
    
script:
    - docker run -e CI=true sunnymishra0389/docker-react-testimage npm run test
    
after_success:
    - docker build -t sunnymishra0389/multi-client ./client
    - docker build -t sunnymishra0389/multi-nginx ./nginx
    - docker build -t sunnymishra0389/multi-server ./server
    - docker build -t sunnymishra0389/multi-worker ./worker

    - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push sunnymishra0389/multi-client
    - docker push sunnymishra0389/multi-nginx 
    - docker push sunnymishra0389/multi-server
    - docker push sunnymishra0389/multi-worker
    
deploy:
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "multi-container-react-app"
    env: "Multicontainerreactapp-env"
    bucket-name: "elasticbeanstalk-ap-south-1-230907580299"
    bucket-path: "multi-docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_KEY_SECRET
